-- MySQL Script generated by MySQL Workbench
-- dom 26 mai 2019 20:52:59 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gerenciamentotarefas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciamentotarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciamentotarefas` DEFAULT CHARACTER SET latin1 ;
USE `gerenciamentotarefas` ;

-- -----------------------------------------------------
-- Table `gerenciamentotarefas`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentotarefas`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `image` VARCHAR(200) NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
